# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: ec2-54-155-92-75.eu-west-1.compute.amazonaws.com
  port: 5432
  database: d3bfc9k19i4ehb
  username: lbpxmaqfpsnuto 
  password: 7025d15b64f0301cdef5b0bd7318a2e6ec387760308bd1a341f910baae5aad2e
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: d3bfc9k19i4ehb


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/d3bfc9k19i4ehb
