class User < ApplicationRecord
    # tells the user model that the password_digest field has to be encrypted
    # has_secure_password makes it so that when we define the password_digest 
    # in the user model it knows to expect a password and a password_confirmation
    # then uses the 'secret key' of the application (generated by the application
    # when it was created) as a salt when hashing the password.
    has_secure_password

    # tells the user model that we are requiring the presence of an email when
    # the user is created.
    validates_presence_of :email 
    # tells the user model that the email that is provided must be unique
    validates_uniqueness_of :email
end
